### ISSUE TITLE
Add permalink to job properties

### ISSUE THREAD

**Issue by gberche-orange** [cppforlife/bosh-hub#2]
The bosh.io rendering of job properties is great, as I start to use it more often, I'd like to be able to reference individual job properties as a reference, and target them with a permalink (in emails, docs)

The github permalink mechanism is very flexible in that it lets users selec specific lines in a file, and updates the url anchor with the selected line numbers:

e.g. https://github.com/cloudfoundry/cf-release/blob/master/jobs/hm9000/spec#L56-L58

Something similar for bosh.io jobs properties would be awesome.

**Comment by cppforlife** [comment]
What do you think about this format:

https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=184#p=agent.blobstore.access_key_id

**Comment by cppforlife** [comment]
Change deployed.

**Comment by gberche-orange** [comment]
Sorry for late reply, was away from office a few days. Thanks a lot Dmitry for this enhancement. The format ``p=<property_from_job_path>`` is already very useful.

I wonder whether the job name should be added to disambiguate when a same property is defined in multiple jobs.

For instance, in cf_release: 
* `cc.internal_api_user` is defined in [hm9000 spec](https://github.com/cloudfoundry/cf-release/blob/9334295133435fa77767651030500d2b0de62611/jobs/hm9000/spec#L40-L42) with description "Username for hm9000 API""
*  `cc.internal_api_user` is defined in [cloud_controller_worker spec](https://github.com/cloudfoundry/cf-release/blob/2b8fcf9e7c45bdfdda3a7b2cef6e7739bce99439/jobs/cloud_controller_worker/spec#L147-L149) with description "User name used by Diego to access internal endpoints"

However, the current permalink ommiting the job name in the url don't allow to reference one or another: https://bosh.io/jobs/cloud_controller_worker?source=github.com/cloudfoundry/cf-release&version=213#p=cc.internal_api_user

Maybe adding the job name as prefix ``p=<job_name>.<property_from_job_path>`` would remove the ambiguity.

**Comment by cppforlife** [comment]
Job is already part of the url: /jobs/name?source...

**Comment by gberche-orange** [comment]
Thanks, missed that in the url prefix.
