### ISSUE TITLE
markdown html rendering lack anchors for headings and page TOC

### ISSUE THREAD

**Issue by gberche-orange** [cppforlife/bosh-hub#3]
On some pages, the markdown rendering that bosh-hub does is lacking anchors for headings. This makes it hard to have docs-bosh have deep relative cross-links among pages.

e.g. https://bosh.io/docs/vm-config.html

I tried comparing markdown formatting for pages that include a TOC and those that don't and did not find something discriminant. I imagine this could be in https://github.com/cppforlife/docs-bosh-io as pointed in [config.yml](https://github.com/cppforlife/bosh-hub/blob/master/docs-bosh-io/config.yml#L2) but this repo does not yet seem public.

**Comment by cppforlife** [comment]
There is no docs-bosh-io repo, it's just this directory in this repo: https://github.com/cppforlife/bosh-hub/tree/master/docs-bosh-io.

Does mini TOC at the top of the <https://bosh.io/docs/vm-config.html> not sufficient?

**Comment by gberche-orange** [comment]
Thanks Dmitry for your reply.

The mini TOC is great and indeed matches my need. What's triggering its presence on a given page ? Is it the presence ``<a id="global"></a>`` in the markdown markup ?

Before https://github.com/cloudfoundry/docs-bosh/commit/1572415da58c4da20619c964aeb00aa2f714115a#diff-5b464ca392ae4a8916dcda708da5f92b it was not appearing on https://bosh.io/docs/vm-config.html

**Comment by cppforlife** [comment]
It's the little a tags.

**Comment by gberche-orange** [comment]
great, thanks, I'll try that in PRs if I see some pages where I miss TOCs
